### ISSUE TITLE
更改email後，下次登入會被視為不同使用者

### ISSUE THREAD

**Issue by requiemformemories** [5xRuby/rubyconftw-cfp#102]
如題，使用者更改email後，下次登入會被當成新使用者。

**Comment by lctseng** [comment]
該不會就是今天寄出來的那個無法修改投稿的問題吧

**Comment by requiemformemories** [comment]
```where(email: auth.info.email).first_or_create do |user|``` in app/models/user.rb
對不起我道歉QWQQQ

**Comment by ryudoawaru** [comment]
解法：

1. 維持以 email 做 user 識別：禁止改 email，但是設定另一個欄位做聯絡用 email
1. 改成用其它方式，例如 username / GH id 做 user 識別，Devise 做的到這件事滴

**Comment by ryudoawaru** [comment]
結論：用 GH id 識別

**Comment by lctseng** [comment]
已在gitlab上修復
