### ISSUE TITLE
新增針對個別 Activity 的權限

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#134]
配合 #60 

需要新增權限的 Table 去達成可以決定「哪些帳號是可以審哪個 Activity 的稿」的這件事

**Comment by jerrylin224** [comment]
以認領issue

**Comment by jerrylin224** [comment]
Hi @ryudoawaru 
我想跟你確認一下關於這個issue的一些事情。

我看裡面有一個 `reviewers_controller.rb`可以把`admin`跟`activity`做關聯。所以應該在`Activity.rb`新增一個`superadmin`的權限，接著透過`reviewers_controller`關聯一般`admin`跟`activity`，最後在`activity`的頁面上寫個`require_reviewer`之類的method應該就可以過濾是否是reviewer了。

所以這樣還有必要新增一個table去做這件事嗎？如果要新增的話，你這個權限的table指的是要像cancan文件一樣獨立的Role table就好嗎？還是不是呢？[Separate Role Model](https://github.com/CanCanCommunity/cancancan/wiki/Separate-Role-Model)

**Comment by ryudoawaru** [comment]
請注意權限是針對個別 acvitity 的喔

至於要不要繼續沿用 ability 都可以，其它請 @elct9620 提供意見

**Comment by jerrylin224** [comment]
Hi @ryudoawaru 
不好意思想再跟你確認一下「請注意權限是針對個別 activity 的喔」這件事。因為透過`reviewers_controller`是可以針對個別activity去選擇可以進入該activity的reviewer，我在create的頁面過濾一下就可以確保選擇出的reviewer是一般admin而不是一般user。
```ruby
# schema.rb
create_table "user_activity_relationships", force: :cascade do |t|
  t.integer  "user_id"
  t.integer  "activity_id"
  t.boolean  "is_reviewer"
  t.datetime "created_at",  null: false
  t.datetime "updated_at",  null: false
end
```

```ruby
# reviewers_controller.rb
def create
  @relationship = UserActivityRelationship.new(relationship_params)
  @relationship.activity_id = @activity.id
end

private

def relationship_params
  params.require(:user_activity_relationship).permit(:user_id)
end
```

想請問一下在這樣的情況下是否有滿足你所說的「權限是針對個別 activity」呢？還是我誤解了你的意思了呢？

**Comment by elct9620** [comment]
@ryudoawaru  @jerrylin224 對，目前這部分是已經有實作的部分。

**Comment by jerrylin224** [comment]
@elct9620 謝謝蒼時，那針對activity新增reviewer權限的部分我就沿用`reviewers_controller`。
