### ISSUE TITLE
投稿數字顯示同步問題

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#29]
![screenshot 2016-10-05 14 24 12](https://cloud.githubusercontent.com/assets/212290/19103140/95971b06-8b07-11e6-933d-e45da6a923c6.png)

上面的是正確的，因為有減掉 Withdraw 的

**Comment by elct9620** [comment]
所以要去掉 Withdraw 的項目？

**Comment by ryudoawaru** [comment]
理論上應該是要 @kaochenlong  覺得？

**Comment by elct9620** [comment]
Navbar 目前是用這個方法算
https://github.com/5xRuby/rubyconftw-cfp/blob/master/app/models/activity.rb#L34

所以 Navbar 的數字其實是以目前 User 的 Review 狀態來決定的

**Comment by ryudoawaru** [comment]
啊啊啊啊啊　那應該先都用還沒棄權的來算好了

**Comment by ryudoawaru** [comment]
在改的話請認領
