### ISSUE TITLE
後台搜尋功能

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#39]
可搜尋條件：
1. 國籍
2. state
3. duration
4. 講者資訊

**Comment by lctseng** [comment]
講者資訊
這是要搜尋哪一個部分？講者的名字？還是Bio？

**Comment by lctseng** [comment]
發現"國家"欄位一堆user的資料是nil。這樣還有搜尋的價值嗎(?

**Comment by lctseng** [comment]
custom field的搜尋我應該會寫死在code裡面，
意思就是選擇搜尋duration時，我就直接用"1"這個key當作custom_field的key。
還是說我要寫成比較通用的做法？
(即：所有custom key都可以搜尋，然後搜尋欄位隨著custom key而改變。)

**Comment by elct9620** [comment]
Custom Field 是每個 Activity 用不同的，這樣寫下一個活動就炸掉了 Orz

**Comment by lctseng** [comment]
所以用後者寫法的話 就會把所有custom都算進去，不能只挑duration來用

**Comment by elct9620** [comment]
因為每次都不確定這個欄位的 Key 跟類型是多少 XD

**Comment by lctseng** [comment]
SQL的like搜尋的部分，我需要預設加上%嗎？
也就是網頁上輸入test
我就搜尋 %test%
還是說，讓使用者自己決定要不要使用跳脫字？(%和_之類的)

**Comment by lctseng** [comment]
附註一下，搜尋tag可以用逗號分隔，會把結果OR起來
