### ISSUE TITLE
取得 Github username

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#40]
總之　因為以前的設計沒考慮到這件事，所以只有拿到 GH id 數字，所以現在要：
1. 加一個 Github username 欄位在 users
2. 寫一個 rake 去把現在沒取得 username 的透過 id 去拿到 username
3. 未來再登入時，自動從 oauth info 裡拿到 username

**Comment by ryudoawaru** [comment]
這不用寫spec ok

**Comment by lctseng** [comment]
被流量限制的部分，應該在each內加上sleep 1就可以解了，只是會跑很久(反正是rake沒差

**Comment by ryudoawaru** [comment]
那沒救了它是 1hr  60 次
production 端已抓完
