### ISSUE TITLE
Comment AJAX 或 Actioncable 化

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#45]
目前加 comment 沒 Ajax 有點不好用

**Comment by lctseng** [comment]
目前先讓增加Comment變成ajax化，其他的comment處理(delete)還是維持原本的操作
這樣OK嗎?

**Comment by lctseng** [comment]
然後目前AJAX只有做在當前使用者新增comment時有效，他人新增的comment還不會即時更新到自己的畫面上。如果ˋ要這個功能，我就要改用action cable了

**Comment by ryudoawaru** [comment]
還好，沒那麼多人XD

**Comment by lctseng** [comment]
所以就維持現在的版本囉？
