### ISSUE TITLE
加 TAG 介面改用 select2 或類似的東西

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#47]
so far 加 TAG 的輸入太不友善了，請用 select2 之類的東西去實作 UI

**Comment by lctseng** [comment]
目前頁面長這樣
![image](https://cloud.githubusercontent.com/assets/6820928/19355297/75c526a6-919c-11e6-93b4-1682dbe14994.png)
有自動補完的功能
