### ISSUE TITLE
Binding notification channels

### ISSUE THREAD

**Issue by marsz** [5xRuby/rubyconftw-cfp#48]
- Each activity can create channels with different service type, such as Slack, Flowdock, Email.
- Each channel should set `name`, `api token/ webhook url`, and optional for `target` (room name or user name).
- A channel can toggle enable / disable.
- A channel can choose events to trigger, such as "New Comment", "New paper", "Paper status changed".
- Message will be send in background.

**Comment by lctseng** [comment]
此功能的初步測試版已經被部署到staging的網站上，可以去測試看看
目前提供slack與email，可以編輯activity時設定通知
目前也沒有防呆機制與input check，請確保輸入資料時正確

**Comment by marsz** [comment]
@lctseng  @ryudoawaru 
幫我開一下 staging admin: `marsz330@gmail.com`

另外，你們會有習慣把 issue 的  PR 也 ref 到 issue 上嗎? (在 comment 貼上 pr link 就可以了)
我自己這邊都會習慣從 issue 追 PR ，所以都會把 PR ref 到 issue 上

**Comment by lctseng** [comment]
@marsz 這個branch還沒發PR，staging用的code再gitlab上不在github
admin權限已開

**Comment by marsz** [comment]
了解了！感謝你 :D  @lctseng

**Comment by lctseng** [comment]
BTW，Notification的text還沒有美化，到時候應該會用slack的syntax/email view template美化
不過需要提供的資料(誰的comment、哪一篇paper)應該都有提供了。確定一下哪些資料應該有而沒有提供(例如activity name)，這樣才有辦法修正

**Comment by marsz** [comment]
@lctseng 已測！太強大惹，沒想到直接用 nested form 幹光光
下次哥再請你吃燒肉！

**Comment by marsz** [comment]
補充一下， notification message 的內容可以帶 link 直接到該 paper 或該 anchor 到該 comment
slack message 的 link 如果不是 direct url 就會需要再另外 formatting

**Comment by lctseng** [comment]
感謝測試XD message內容的部分會再處理

**Comment by lctseng** [comment]
@marsz Slack message的formatting已經弄好了，此外data validate也加上了(設定notifier欄位時必填欄位不能留白)，東西都在staging的網站上，有空可以去review一下
