### ISSUE TITLE
paper model validation造成部分已進入資料庫的paper無法更新/save

### ISSUE THREAD

**Issue by lctseng** [5xRuby/rubyconftw-cfp#49]
paper model validation用10 char當作驗證，但事實上應該是用10 words。
導致某些已經送出的paper(例如ID = 2的這篇，speaker_bio: "Ruby and Rails programmer from Taiwan",)
長度不足，造成任何之後的update/save都會失敗。

**Comment by elct9620** [comment]
Paper Model 現在的 Validation 用的是 word 去計算喔⋯⋯

**Comment by lctseng** [comment]
神奇吧。不知道是誰改der

**Comment by elct9620** [comment]
我改的啊 O____O

之前有一個 Feature 就是這個，沒記錯是 #1 這個 Issue 要改的啊 XD

**Comment by lctseng** [comment]
可是production的資料庫內有違反validation的資料，你要如何處理?

**Comment by elct9620** [comment]
Production 裡面有違反的！？這段我就沒追到了⋯⋯

**Comment by lctseng** [comment]
我猜這是你的validation是後來才加上去的。我用總召給的db dump，裡面paper id = 2這篇就違反了。

**Comment by elct9620** [comment]
是上 Production 之後才補的，因為有講者反應這樣 XD
不過我手邊沒有 Production 的 dump 資料所以不知道這件事。

**Comment by lctseng** [comment]
slack上有production db dump。去套套看吧

**Comment by elct9620** [comment]
不過我覺得這個問題就人工處理一下就可以了 XD

**Comment by lctseng** [comment]
是沒錯。但得進入production資料庫處理。這個重責大任就交給你了(?

**Comment by lctseng** [comment]
測試了一下，應該只有剛剛提到的那一筆有違反。

**Comment by elct9620** [comment]
再說吧（遠望
不過我也沒有進去 DB 的權限啊 XD

**Comment by ryudoawaru** [comment]
那筆我後來叫他改了所以最新的資料是正確的，你 local 先自己改改吧

**Comment by lctseng** [comment]
ok
