### ISSUE TITLE
Add Review  state 

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#60]
原本的 Review 只有顯示「我審過稿了」的這個狀態，沒有投贊成或反對的功能
![screenshot 2017-09-13 18 04 16](https://user-images.githubusercontent.com/212290/30371752-20a11710-98ae-11e7-9478-a378e82a2d62.jpg)

需要增加：

1. Review 的狀態，分成贊成和不贊成
1. 針對以上功能在後台管理介面對應的修改

**Comment by jerrylin224** [comment]
以認領issue

**Comment by jerrylin224** [comment]
Hi @ryudoawaru 

我想跟你確認一下這個issue，這個issue是要讓每個reviewer都能夠審稿（投贊成/反對票），那最終稿件是否通過（accept/reject）這件事應該是落在superadmin身上。

這個feature有要限制所有reviewer都投票完畢後，superadmin才能決定是否通過這個稿，還是superadmin隨時都可以accept/reject呢？

**Comment by ryudoawaru** [comment]
這個 issue 沒有要做最後是否通過的功能喔
