### ISSUE TITLE
[未來]和 Devise 脫鉤

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#61]
目前 User 架構是 Devise，未來應該和它脫鉤

主要目的：同一 User 可以用多種 OAuth 登入

等 rubyconf 告一段落再說

**Comment by elct9620** [comment]
抽象化還是自己實作過？

**Comment by ryudoawaru** [comment]
自己實作，但要保留現有 User 資料，而且要可以用多種 OAuth 登入

**Comment by elct9620** [comment]
不過一般不是都用 Devise 處理 User 問題，有必要特別自己實做出來嗎？

OmniAuth 可以跟 Devise 分開使用，保留多種 OAuth 登入功能應該沒有太大的影響。

**Comment by ryudoawaru** [comment]
還沒仔細研究過，但是目前 Devise 這個表長的樣子要同一 User 用多種 OAuth 登入應該有難度？

**Comment by elct9620** [comment]
這是目前實作的方式造成的，多重 OAuth 登入一般是用 `has_many` 的方式。

User -> has_many -> AuthProvider

一般登入走 Devise 如果是 OmniAuth 是從 AuthProvider 配對完畢撈 User 出來 XD

**Comment by ryudoawaru** [comment]
這樣的話，是可以繼續用
