### ISSUE TITLE
subdomain or fqdn for each activity

### ISSUE THREAD

**Issue by marsz** [5xRuby/rubyconftw-cfp#63]
- An activity should auto generate subdomain after create (uniqueness in all activities)
- Subdomain can customize in admin (still should be uniqueness)
- Activity can set fqdn and be optional attribute.
- Subdomain or fqdn should be works while set `*.rubyconf.tw` and `*` available domain names in  web server config file (e.g. nginx).
- The root page in each activity will route to `activities#show` in Rails app.

**Comment by elct9620** [comment]
#62 可能要一起討論，都會用到 subdomain 去處理，設計上要看怎麼調整。

**Comment by ryudoawaru** [comment]
暫時沒要做先 close
