### ISSUE TITLE
搜尋同時具有複數 TAG 的投稿

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#64]
在 Papers->Index 的搜尋介面上，可以一次搜尋「同時具有一或多個 TAG 的投稿」

輸入 TAG 部份可以跟 show 裡面用的一樣

**Comment by ryudoawaru** [comment]
希望可以在明天審稿會議前出版

**Comment by ryudoawaru** [comment]
另外在 TABLE 的上面可以顯示這次搜尋有幾筆資料

**Comment by lctseng** [comment]
@ryudoawaru 是指輸入tag A和B，就要搜尋同時擁有A和B tag的某一篇paper這樣嗎?

**Comment by ryudoawaru** [comment]
YES, 是 and

**Comment by lctseng** [comment]
PR已出，local測試上功能應該沒問題
