### ISSUE TITLE
[未來] Custom field的filed name不應該與固定的search field重複

### ISSUE THREAD

**Issue by lctseng** [5xRuby/rubyconftw-cfp#65]
search系統提供搜尋custom field，但由field名字判斷。
優先判斷fixed file (例如title, tags)，導致重複名稱發生時，搜尋不到custom field

**Comment by elct9620** [comment]
覺得要從改進 Custom Field 的設計下手

**Comment by savinachan** [comment]
想請問這邊要在Custom field的filed name那邊阻止它跟固定的search field一模一樣嗎？

**Comment by elct9620** [comment]
對，因為重複的時候會被蓋掉造成搜尋不到。
