### ISSUE TITLE
寄信時 bcc 給特定 email address

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#71]
寄信給講者時 bcc 給 settings 列的 email，key 為 bcc_email

**Comment by ryudoawaru** [comment]
@elct9620 或 @lctseng 看誰可以先幫忙趕一下這一條，急需 XD

**Comment by elct9620** [comment]
我弄一下，半夜應該可以出來 XD

**Comment by elct9620** [comment]
@lctseng 你有改到什麼嗎？怎麼 Development 模式不會跳假 Mail 而是直接進去 ActionJob 惹（囧

**Comment by elct9620** [comment]
@lctseng  https://github.com/5xRuby/rubyconftw-cfp/blob/master/config/email.yml

這樣用不好吧 O____O

**Comment by lctseng** [comment]
@elct9620  大大，你有看檔案作者嗎?
git blame應該會告訴你上次的作者吧？

**Comment by lctseng** [comment]
我一直都用假mail啊，要不然怎麼會需要到staging上測試notification?

**Comment by elct9620** [comment]
喔喔，看到了 Orz

原來有歷史的共業在裡面，因為剛剛快速弄過一遍所以沒有 git blame XD
