### ISSUE TITLE
YAML EXPORT 問題

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#75]
1.  多餘欄位太多，只留下現有欄位與語言
2.  欄位名稱不對，例如 avatar
3.  目前這包會有 escape 問題
4.  匯出圖檔路徑時，請包含 hostname，但 scheme 請不要指定（用 `//` 開頭）

資料包我會丟在 Slack

**Comment by lctseng** [comment]
現有欄位是指甚麼？當前paper schema中的attributes嗎?
然後escape問題是甚麼意思？印出來的文字排版不好？
圖檔路徑的部分，正確的路徑可以給個example嗎？

**Comment by ryudoawaru** [comment]
-  現有欄位：https://github.com/rubytaiwan/2016/blob/master/data/speaker.yml
-  你把匯出的拿到上面那個 repo （conf 官網）去跑看看, 跑之前先 npm install -> npm run serve
-  example: `//cfp.rubyconf.tw/uploads/user/photo/7/icon-256.png`

**Comment by lctseng** [comment]
所以這個匯出yaml是拿來塞資料到conf官網上的？

**Comment by ryudoawaru** [comment]
yeah~~~
