### ISSUE TITLE
Docker 化

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/rubyconftw-cfp#95]
請參照 https://github.com/5xRuby/5xruby.tw/pull/57

**Comment by elct9620** [comment]
因為 `.gitignore` 的關係，Dockerfile 在 5xRuby/5xruby.tw#58 這個 PR

**Comment by ryudoawaru** [comment]
還沒做的話我來加囉

**Comment by lctseng** [comment]
你加吧XD

**Comment by elct9620** [comment]
需要補文件 & 改善，有人因為沒有文件被雷到這樣⋯⋯

**Comment by elct9620** [comment]
`upload` 目錄要用 Volume 掛在外面

**Comment by ryudoawaru** [comment]
之前好像不是用 Volume 的

**Comment by elct9620** [comment]
之前因為是把整個 `app` 掛外面所以沒用到，不過正常 Dockerize 的話其實是要這樣處理的

**Comment by elct9620** [comment]
這個還有 Bug 還是要另外開個 Issue 寫 Bug？

**Comment by ryudoawaru** [comment]
不是 #106 嗎？

**Comment by elct9620** [comment]
這邊還有 `volume` 沒掛到的問題 XD

**Comment by ryudoawaru** [comment]
那就加 issue
